## This is the frontned server deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bltang-playlist-recommender
  template:
    metadata:
      labels:
        app: bltang-playlist-recommender
    spec:
      containers:
      - name: playlist-recommender
        image: beilongtang/playlists-recommender-system:0.4
        env:
        - name: APP_VERSION # APP Version
          value: '0.4'
        ports:
        - containerPort: 52006
        volumeMounts:
        - mountPath: "/ml_data"
          name: storage
      volumes: 
        - name: storage
          persistentVolumeClaim:
            claimName: project2-pvc-beilong

## This is the backend server deployment
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ml-generator-2
spec:
  template:
    metadata:
      labels:
        app: bltang-ml-generator
    spec:
      containers:
      - name: ml-rules
        image: beilongtang/ml_rules:0.3
        env:
        - name: DATA_PATH  # DATA PATH
          value: "/ml_data/2023_spotify_ds2.csv"  # Can change the dataset name to simulate update. 
        volumeMounts:
        - mountPath: "/ml_data"
          name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: project2-pvc-beilong
      restartPolicy: OnFailure  # Valid for Jobs
