apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-service
spec:
  selector:
    app: bltang-playlist-recommender
  ports:
    - protocol: TCP
      port: 52006
      targetPort: 52006